version: '3.7'

services:
  django:
    build: .
    image: django_image:test
    user: www-data
    expose:
      - "8001"
    volumes:
      - ./code:/code
    environment:
      - TZ=Asia/Tokyo
      - DJANGO_NAME=${DJANGO_NAME}
      - DJANGO_SPAPP=${DJANGO_SPAPP}
      - CLEARSITE=$CLEARSITE
    restart: always
  nginx:
    image: nginx:alpine
    expose:
      - "80"
    ports:
      - "8000:80"
    depends_on:
      - django
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./code:/code:ro
      - ./nginx/90_delay_mount.sh:/docker-entrypoint.d/90_delay_mount.sh:ro
      #- ./code/${DJANGO_NAME}/static:/static:ro
    environment:
      - TZ=Asia/Tokyo
      - DJANGO_NAME=${DJANGO_NAME}
    restart: always

