version: '3.7'

services:
  django:
    build: .
    image: django_image:test
    user: www-data
    expose:
      - "8001"
    volumes:
      - ./code:/code
    environment:
      - TZ=Asia/Tokyo
      - DJANGO_NAME=${DJANGO_NAME}
      - DJANGO_SPAPP=${DJANGO_SPAPP}
      - CLEARSITE=$CLEARSITE
    healthcheck:
      test: ["CMD-SHELL", "ps x | grep uwsgi | grep -v grep"]
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 2s
    restart: always
  nginx:
    image: nginx:alpine
    expose:
      - "80"
    ports:
      - "8000:80"
    depends_on:
      django:
        condition: service_healthy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./code/${DJANGO_NAME}/static:/static:ro
    environment:
      - TZ=Asia/Tokyo
      - DJANGO_NAME=${DJANGO_NAME}
    restart: always

