#!/bin/bash
echo project name is $DJANGO_NAME .
#
sudo chown www-data.www-data . || exit 1

if [ -z $DJANGO_NAME ]; then
    echo env:DJANGO_NAME must be defined as project name.
    exit 1
fi

# construction of main project if not exist project directory
if [ ! -d $DJANGO_NAME ]; then
    echo project folder '$DJANGO_NAME' is not exist, now initialize project.
    # Initialize django project name as 
    django-admin startproject $DJANGO_NAME
    # edit settings.py
    pushd ${DJANGO_NAME}/${DJANGO_NAME}
    if [ -f settings.py ]; then
        echo Edit settings.py ....
        cat settings.py \
            | sed -r "s/^ALLOWED_HOSTS.+$/ALLOWED_HOSTS \= \['*'\]/g" \
            | sed -r "/^USE_TZ = True$/iUSE_L10N = True\n" \
            | sed -r "s/^LANGUAGE_CODE = .+$/LANGUAGE_CODE = 'ja-JP'/g" \
            | sed -r "s/TIME_ZONE = .+$/TIME_ZONE = 'Asia\/Tokyo'/g" > tmpfile
        rm settings.py
        mv tmpfile settings.py
    fi
    popd
fi

# enter to project directory. exit if not exist target directory.
cd ${DJANGO_NAME} || exit 1
if [ ! -z ${DJANGO_SPAPP} ] && [ ! -d ${DJANGO_SPAPP} ]; then
    python manage.py startapp ${DJANGO_SPAPP}
    APPCAP=$(echo ${DJANGO_SPAPP} | sed 's/\(.\)\(.*\)/\U\1\L\2/g')
    APPCONFIG=${DJANGO_SPAPP}.apps.${APPCAP}Config
    pushd ${DJANGO_NAME}
    # edit settings.py
    cat settings.py \
        | sed -zr "s/(\nINSTALLED_APPS = \[\n)/\1    '${APPCONFIG}',\n/g" \
        | sed -zr "s/(\nINSTALLED_APPS = \[\n[^]]*)(\])/\1    'tinymce',\n    'django_bootstrap5',\n\2/g" > tmpfile
        rm settings.py
        mv tmpfile settings.py
    # edit urls.py
    cat urls.py \
        | sed -r "s/^(from django.urls import ).+$/\1include, path/g" \
        | sed -r "/^urlpatterns/iimport tinymce\n" \
        | sed -zr "s/(\nurlpatterns = \[[^]]*)(\])/\1    path('', include('${DJANGO_SPAPP}.urls')),\n\2/g" \
        | sed -zr "s/(\nurlpatterns = \[[^]]*)(\])/\1    path('tinymce\/', include('tinymce.urls')),\n\2/g" > tmpfile
    rm urls.py
    mv tmpfile urls.py
    popd
fi

# bootstrap などスタティック領域初期化
CUSTOM_SCSS=bootstrap-custom.scss
CUSTOM_CSS=bootstrap-custom.css
if [ ! -d 'static' ]; then mkdir static; fi
pushd static
if [ ! -d 'css' ]; then mkdir css; fi
cd css

# bootstrap 導入
# シンボリックリンクでは静的アクセス(nginx service)からアクセス出来ない
# 問題があったのでコピーに変更
if [ ! -d 'bootstrap' ]; then
    rm -rf bootstrap
fi
cp -rf /usr/local/lib/node_modules/bootstrap .

# カスタムSCSSのテンプレート作成と監視型コンパイラ起動
if [ ! -f ${CUSTOM_SCSS} ]; then
    cat <<EOS > ${CUSTOM_SCSS}
/*
$ sass bootstrap-custom.scss bootstrap-custom.css
*/
@import "bootstrap/scss/bootstrap.scss";
EOS
fi
sass --watch ${CUSTOM_SCSS}:${CUSTOM_CSS} &
popd

# jsディレクトリ更新:bootstrapなどからのリンク生成
pushd static
if [ ! -d 'js' ]; then mkdir js; fi
cd js
# シンボリックリンクを張り直す
find . -maxdepth 1 -type l -delete
ln -s ../css/bootstrap/dist/js/* .
popd

# uwsgiデーモン起動
uwsgi --socket :8001 --module ${DJANGO_NAME}.wsgi --uid www-data --py-autoreload 1
